-- AlterTable
ALTER TABLE "ProgressPhoto" ADD COLUMN IF NOT EXISTS "sharedWithCoach" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ProgressPhoto" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "BodyMeasurement" ADD COLUMN IF NOT EXISTS "neck" DOUBLE PRECISION;
ALTER TABLE "BodyMeasurement" ADD COLUMN IF NOT EXISTS "shoulders" DOUBLE PRECISION;
ALTER TABLE "BodyMeasurement" ADD COLUMN IF NOT EXISTS "bicepL" DOUBLE PRECISION;
ALTER TABLE "BodyMeasurement" ADD COLUMN IF NOT EXISTS "bicepR" DOUBLE PRECISION;
ALTER TABLE "BodyMeasurement" ADD COLUMN IF NOT EXISTS "forearmL" DOUBLE PRECISION;
ALTER TABLE "BodyMeasurement" ADD COLUMN IF NOT EXISTS "forearmR" DOUBLE PRECISION;
ALTER TABLE "BodyMeasurement" ADD COLUMN IF NOT EXISTS "thighL" DOUBLE PRECISION;
ALTER TABLE "BodyMeasurement" ADD COLUMN IF NOT EXISTS "thighR" DOUBLE PRECISION;
ALTER TABLE "BodyMeasurement" ADD COLUMN IF NOT EXISTS "calfL" DOUBLE PRECISION;
ALTER TABLE "BodyMeasurement" ADD COLUMN IF NOT EXISTS "calfR" DOUBLE PRECISION;
ALTER TABLE "BodyMeasurement" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "MealPlan" ADD COLUMN IF NOT EXISTS "goal" TEXT;
ALTER TABLE "MealPlan" ADD COLUMN IF NOT EXISTS "days" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "MealPlan" ADD COLUMN IF NOT EXISTS "createdBy" TEXT NOT NULL DEFAULT '';
ALTER TABLE "MealPlan" ADD COLUMN IF NOT EXISTS "assignedTo" TEXT;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "MealPlan_assignedTo_idx" ON "MealPlan"("assignedTo");

-- AlterTable
ALTER TABLE "Meal" ADD COLUMN IF NOT EXISTS "day" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Meal" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Meal" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
