-- AlterTable
ALTER TABLE "Exercise" ADD COLUMN IF NOT EXISTS "modality" TEXT,
ADD COLUMN IF NOT EXISTS "movementPattern" TEXT,
ADD COLUMN IF NOT EXISTS "primaryMuscles" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "secondaryMuscles" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "bodyRegion" TEXT,
ADD COLUMN IF NOT EXISTS "equipmentCategory" TEXT,
ADD COLUMN IF NOT EXISTS "equipmentDetail" TEXT,
ADD COLUMN IF NOT EXISTS "difficulty" TEXT,
ADD COLUMN IF NOT EXISTS "impactLevel" TEXT,
ADD COLUMN IF NOT EXISTS "environment" TEXT,
ADD COLUMN IF NOT EXISTS "goalTags" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "loggingOptions" TEXT[] DEFAULT ARRAY[]::TEXT[];

